### ISSUE TITLE
seems to be over retracting without marker

### ISSUE THREAD

**Issue by jmerc77** [Sakati84/3DPrintColorizer#36]
when there's no marker an its extruding the retracts are longer then the detracts. may vary on the retraction during painting value. still trying to find exact cause...

**Comment by jmerc77** [comment]
retraction during painting = 0 did not help this.

**Comment by Sakati84** [comment]
Hi, there was a new pull request for the cura Profile which should fix this. You can redownload and Import the Profile or just disable "retract on layer change" in cura.

**Comment by jmerc77** [comment]
tried turning off "retract on layer change" but still having the problem. also there are z-hops when z-hop is disabled. another problem is M900 for linear advance on each tool. should be only one tool.
[gcode.txt](https://github.com/Sakati84/3DPrintColorizer/files/6977194/gcode.txt)

**Comment by jmerc77** [comment]
oh I forgot to mention, sometimes it would print slow but sometimes fast. varying feedrate?

**Comment by jmerc77** [comment]
hay! randomly started working. I think it was the wall count?? the M900 is still a problem though. I'll post separate issue. although not effecting print quality so far and no warnings.
